- build: 3.4.6/centos/7
  image:
    - mesoscloud/zookeeper:3.4.6-centos-7
    - mesoscloud/zookeeper:3.4.6-centos
    - mesoscloud/zookeeper:3.4.6
    - mesoscloud/zookeeper:latest

- build: 3.4.6/ubuntu/14.04
  image:
    - mesoscloud/zookeeper:3.4.6-ubuntu-14.04
    - mesoscloud/zookeeper:3.4.6-ubuntu


- tests:
    - cmd: zkServer.sh print-cmd
